# Generated by Django 4.2.5 on 2023-09-29 19:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Hackaton',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ciclo', models.CharField(blank=True, default='Y23C2', max_length=25)),
                ('Conferencia', models.CharField(choices=[('Aula', 'Aula'), ('Laboratorio', 'Laboratorio')], max_length=25)),
                ('Estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
